%% Sample Headers - Just copied output from a pedant run
-define(SAMPLE_HEADERS, {21,
{<<"x-ops-authorization-6">>,{<<"X-Ops-Authorization-6">>,<<"0xQYdumxPxAhIiTIGsd/46JCM3hv7zuPZhXI/Ii1QQ==">>},
{<<"x-ops-authorization-5">>,{<<"X-Ops-Authorization-5">>,<<"ZLQSuIvjslrXbbvn+AJAPgbFvErRE1O0XHWCGwq8kJoQconeEWJ50p6t5tS0">>},
{<<"x-ops-authorization-1">>,{<<"X-Ops-Authorization-1">>,<<"eCKwfczcgxrM0X/SCCL1pKQVqpWVHgItwEYVafmFP055xe1a54h7oQWPTvk2">>},
{<<"user-agent">>,{'User-Agent',<<"chef-pedant rspec tests">>},
{<<"content-type">>,{'Content-Type',<<"application/json">>},
{<<"accept-encoding">>,{'Accept-Encoding',<<"gzip, deflate">>},
{<<"accept">>,{'Accept',<<"application/json">>},nil,nil},
{<<"connection">>,{'Connection',<<"close">>},nil,nil}},
{<<"host">>,{'Host',<<"private-chef.opscode.piab">>},nil,nil}},
{<<"x-chef-version">>,{<<"X-Chef-Version">>,<<"11.4.0">>},nil,
{<<"x-forwarded-proto">>,{<<"X-Forwarded-Proto">>,<<"https">>},
{<<"x-forwarded-for">>,{'X-Forwarded-For',<<"127.0.1.1">>},nil,nil},nil}}},
{<<"x-ops-authorization-3">>,{<<"X-Ops-Authorization-3">>,<<"wqCEMq8Al25S7KTCrs18fuMUnFQOX/ZKPGYmTMPM9/wcAC18zknM5OQ+oBKZ">>},
{<<"x-ops-authorization-2">>,{<<"X-Ops-Authorization-2">>,<<"ckNJM4K11ILgJU8lI119/B33IPEtnzOXrTuB1vkeYlkKSyNvdTlMo2jTWljw">>},nil,nil},
{<<"x-ops-authorization-4">>,{<<"X-Ops-Authorization-4">>,<<"7Oq75HE2nO2cmFf1+y69fUFOChopW1/KQGvY1UAaInJ/SAqXGXPYBawqKnfF">>},nil,nil}}},nil},
{<<"x-ops-content-hash">>,{<<"X-Ops-Content-Hash">>,<<"2jmj7l5rSw0yVb/vlWAYkK/YBwk=">>},nil,
{<<"x-ops-timestamp">>,{<<"X-Ops-Timestamp">>,<<"2013-05-30T20:32:49Z">>},
{<<"x-ops-sign">>,{<<"X-Ops-Sign">>,<<"algorithm=sha1;version=1.0;">>},
{<<"x-ops-reporting-protocol-version">>,{<<"X-Ops-Reporting-Protocol-Version">>,<<"0.1.0">>},nil,nil},nil},
{<<"x-ops-userid">>,{<<"X-Ops-Userid">>,<<"pedant_admin_user">>},nil,
{<<"x-real-ip">>,{<<"X-Real-Ip">>,<<"127.0.1.1">>},nil,nil}}}}}}).
